version: '3.8'

services:
  neo4j:
    image: neo4j:5 # 最新の5.x系安定版を推奨
    container_name: nvt_ws_neo4j
    ports:
      - "7474:7474" # Neo4j Browser (HTTP)
      - "7687:7687" # Bolt Driver Port
    volumes:
      - neo4j_data:/data
      - ./init:/init # 初期化スクリプト用 (任意)
    environment:
      # 開発中は認証を無効化すると手軽 (本番環境では必ず有効化)
      - NEO4J_AUTH=none
      # または初期パスワード設定:
      # - NEO4J_AUTH=neo4j/your_strong_password
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  neo4j_data:
    driver: local